spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/retailintel
spring.datasource.username=retailintel
spring.datasource.password=retailintel

spring.jpa.hibernate.ddl-auto=validate

# Temporary Hibernate SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE